# Generated by Django 4.1.6 on 2023-02-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ph_number', models.CharField(max_length=14, unique=True)),
                ('dob', models.DateField()),
                ('user_profile', models.ImageField(upload_to='profilesPictures')),
                ('isRider', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('A', 'Bike'), ('B', 'car')], max_length=1)),
                ('vehicle_number', models.CharField(max_length=21, unique=True)),
                ('vehicle_photo', models.ImageField(upload_to='vehiclePictures')),
                ('billbook_page2', models.ImageField(upload_to='billbookPictures')),
                ('billbook_page3', models.ImageField(upload_to='billbookPictures')),
                ('billbook_page9', models.ImageField(upload_to='billbookPictures')),
                ('license_number', models.IntegerField(unique=True)),
                ('license_photo', models.ImageField(upload_to='LicensePictures')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideSharing.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='riderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_number', models.CharField(max_length=20, unique=True)),
                ('citizenship_photo_back', models.ImageField(upload_to='citizenshipPictures')),
                ('citizenship_photo_front', models.ImageField(upload_to='citizenshipPictures')),
                ('id_confirmation_photo', models.ImageField(upload_to='idConfirmationPictures')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideSharing.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='rideInfo',
            fields=[
                ('rideId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('O', 'Open'), ('OC', 'Occupied'), ('X', 'Canclled'), ('C', 'Complete')], default='O', max_length=2)),
                ('geometry', models.JSONField(default=dict)),
                ('formatted_address', models.CharField(max_length=150)),
                ('place_id', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideSharing.userinfo')),
            ],
        ),
    ]
